version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    container_name: db

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env    

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/lab3
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres_data: